image: debian

before_script:
  - apt-get update -qq
  - apt-get install -y -qq python3-pyqt5 python3-numpy python3-matplotlib

stages:
  - test
  - pages

test:
  script:
  - export PYTHONPATH=$PYTHONPATH:.
  - python3 setup.py test

pages:
  script:
  - pip3 install -r apidocs/requirements.txt
  - mkdir public
  - sphinx-build -a -b html ./apidocs ./public/
  artifacts:
    paths:
    - public
  only:
  - master

