image: debian

before_script:
  - apt update -qq
  - apt install -y -qq python3-pip python3-dev python3-pyqt5 python3-pyqt5.qtsvg python3-matplotlib python3-numpy python3-pytest

stages:
  - test
  - pages

test_debian_testing:
  image: debian:testing
  variables:
    QT_QPA_PLATFORM: "offscreen"
  script:
  - mkdir -p /tmp/runtime-pyspreadci
  - export XDG_RUNTIME_DIR=/tmp/runtime-pyspreadci
  - py.test-3

test_debian_unstable:
  image: debian:unstable
  variables:
    QT_QPA_PLATFORM: "offscreen"
  script:
  - mkdir -p /tmp/runtime-pyspreadci
  - export XDG_RUNTIME_DIR=/tmp/runtime-pyspreadci
  - py.test-3

test_debian_experimental:
  image: debian:experimental
  variables:
    QT_QPA_PLATFORM: "offscreen"
  script:
  - mkdir -p /tmp/runtime-pyspreadci
  - export XDG_RUNTIME_DIR=/tmp/runtime-pyspreadci
  - py.test-3

pages:
  image: debian:testing
  script:
  - pip3 install -r apidocs/requirements.txt
  - mkdir public
  - sphinx-build -a -b html ./apidocs ./public/
  artifacts:
    paths:
    - public
  only:
  - master

